replicaCount: 1

image:
  pullPolicy: Always


secrets:
  dbUsername: postgres
  dbPassword: "4015"
  jwtSecret: "32c01665f78c028b589634e3c4ea96a7718356ade9a6ecc34abf0c208adfa0ee"


resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi


probes:

  startup:
    initialDelaySeconds: 40
    periodSeconds: 5
    failureThreshold: 30

  liveness:
    initialDelaySeconds: 40
    periodSeconds: 10

  readiness:
    initialDelaySeconds: 40
    periodSeconds: 5



database:

  image: postgres:17

  storage: 5Gi



apiGateway:

  image:
    repository: ineutrono/ecm-api-service
    tag: latest

  service:
    port: 9000
    nodePort: 30090

  nodePort: 30000

  allowedOrigins: "http://192.168.49.2:30090,http://international-commerce.local,http://192.168.49.2:30099"



user:

  image:
    repository: ineutrono/ecm-user-service
    tag: latest

  service:
    port: 9002



cart:

  image:
    repository: ineutrono/ecm-cart-service
    tag: latest

  service:
    port: 9003



product:

  image:
    repository: ineutrono/ecm-product-service
    tag: latest

  service:
    port: 9001



order:

  image:
    repository: ineutrono/ecm-order-service
    tag: latest

  service:
    port: 9004



payment:

  image:
    repository: ineutrono/ecm-payment-service
    tag: latest

  service:
    port: 9005



frontend:

  image:
    repository: ineutrono/ecm-frontend-service
    tag: latest

  service:
    port: 3000
    nodePort: 30099




redis:

  replicaCount: 1

  image:
    repository: redis
    tag: 7-alpine

  service:
    port: 6379


  resources:

    requests:
      cpu: 50m
      memory: 64Mi

    limits:
      cpu: 250m
      memory: 256Mi


  probes:

    liveness:
      initialDelaySeconds: 10
      periodSeconds: 10

    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5



frontendConfig:
  apiProxyTarget: "http://ecommerce-api-gateway-service:9000"

  allowedOrigins:
    - "http://192.168.49.2:30090"
    - "http://international-commerce.local"



ingress:

  enabled: true

  className: nginx

  host: international-commerce.local