apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-cart-db
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{ include "ecommerce.selectorLabels" . | nindent 4}}
    app: cart-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecommerce-v2

spec:
  selector:
    app: cart
  ports:
    - port: 9003
      targetPort: 9003
  type: ClusterIP
