apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-frontend-config
  namespace: {{ .Release.Namespace}}
data:
  FRONTEND_API_PROXY_TARGET: "http://api-gateway:9000"
  API_ALLOWED_ORIGIN_PATTERNS: {{ .Values.apiGateWay.allowedOrigins | quote }}

