apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "ecommerce.selectorLabels" . | nindent 4 }}
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30090
  type: NodePort
