route:
  receiver: telegram-notifications
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1m
receivers:
  - name: telegram-notifications
    telegram_configs:
      - bot_token: "8806627768:AAGET_smgFZJ0RWGB9LA33iKrN-SJy1bAyc"
        chat_id: 5535089238
        send_resolved: true