services:
  prometheus:
    image: prom/prometheus:latest
    container_name: Prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/targets:/etc/prometheus/targets
      - ./prometheus/rules:/etc/prometheus/rules
    networks:
      - monitoring-net
      - backend-net
    restart: unless-stopped


  postgres-exporter-accounts:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter-accounts
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:4015@accounts_db:5432/accounts_db?sslmode=disable"
    ports:
      - "9181:9187"
    networks:
      - monitoring-net
      - database-net
    restart: unless-stopped


  postgres-exporter-products:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter-product
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:4015@products_db:5432/products_db?sslmode=disable"
    ports:
      - "9182:9187"
    networks:
      - monitoring-net
      - database-net
    restart: unless-stopped

  postgres-exporter-orders:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter-orders
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:4015@order_db:5432/order_db?sslmode=disable"
    ports:
      - "9183:9187"
    networks:
      - monitoring-net
      - database-net
    restart: unless-stopped

  postgres-exporter-cart:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter-cart
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:4015@cart_db:5432/cart_db?sslmode=disable"
    ports:
      - "9184:9187"
    networks:
      - monitoring-net
      - database-net
    restart: unless-stopped

  postgres-exporter-payment:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter-payment
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:4015@payment_db:5432/payment_db?sslmode=disable"
    ports:
      - "9185:9187"
    networks:
      - monitoring-net
      - database-net
    restart: unless-stopped



  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    networks:
      - monitoring-net
    depends_on:
      - prometheus
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards



  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor

    ports:
      - "8085:8080"

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

    privileged: true

    restart: unless-stopped

    networks:
      - monitoring-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/alertmanager
    env_file:
      - .env
    networks:
      - monitoring-net





