apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-order-config
  namespace: {{ .Release.Namespace }}

data:
  ORDER_SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "ecommerce.fullname" . }}-order-db:5432/order_db"

  ORDER_POSTGRES_DB: "order_db"

  ORDER_CART_SERVICE_URL: "http://{{ include "ecommerce.fullname" . }}-cart-service:{{ .Values.cart.service.port }}"

  ORDER_PORT: {{ .Values.order.service.port | quote }}

  API_ORDER_SERVICE_URL: "http://{{ include "ecommerce.fullname" . }}-order-service:{{ .Values.order.service.port }}"