apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-order-config
  namespace: {{ .Release.Namespace}}

data:
  ORDER_SPRING_DATASOURCE_URL: "jdbc:postgresql://international-ecommerce-database.c63e8owqifyk.us-east-1.rds.amazonaws.com:5432/order_db"
  ORDER_POSTGRES_DB: "order_db"
  ORDER_CART_SERVICE_URL: "http://cart-service:9003"
  ORDER_PORT: "9004"
  API_ORDER_SERVICE_URL: "http://order-service:9004"