apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" .}}-order-db
  namespace: {{ .Release.Namespace}}
spec:
  selector:
    {{ include "ecommerce.selectorLabels" . | nindent 4}}
    app: order-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{include "ecommerce.fullname" .}}-order-service
  namespace: {{ .Release.Namespace}}

spec:
  selector:
    {{ include "ecommerce.selectorLabels" . | nindent 4}}
    app: order
  ports:
    - port: 9004
      targetPort: 9004
  type: ClusterIP
