# Local connections
local   all             all                                     trust

# Normal database connections
host    all             all             0.0.0.0/0               scram-sha-256

# Replication connection
host    replication     replicator      0.0.0.0/0               scram-sha-256