apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - redis.yaml
  - auth.yaml
  - product.yaml
  - cart.yaml
  - order.yaml
  - payment.yaml
  - api.yaml
  - frontend.yaml
