apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-v2
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: "4015"
  JWT_SECRET: "32c01665f78c028b589634e3c4ea96a7718356ade9a6ecc34abf0c208adfa0ee"
