#server config
server.port=${PORT:9003}
#database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cart_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:4015}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#secrets
jwt.secret=32c01665f78c028b589634e3c4ea96a7718356ade9a6ecc34abf0c208adfa0ee
