apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-product-config
  namespace: {{ .Release.Namespace}}
data:
  PRODUCT_SPRING_DATASOURCE_URL: "jdbc:postgresql://international-ecommerce-database.c63e8owqifyk.us-east-1.rds.amazonaws.com:5432/products_db"
  PRODUCTS_POSTGRES_DB: "products_db"
  PRODUCT_REDIS_HOST: "redis"
  PRODUCT_REDIS_PORT: "6379"
  PRODUCT_PORT: "9001"
  API_PRODUCT_SERVICE_URL: "http://product-service:9001"