apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-product-config
  namespace: {{ .Release.Namespace }}

data:
  PRODUCT_SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "ecommerce.fullname" . }}-product-db:5432/products_db"

  PRODUCTS_POSTGRES_DB: "products_db"

  PRODUCT_REDIS_HOST: "{{ include "ecommerce.fullname" . }}-redis"

  PRODUCT_REDIS_PORT: "6379"

  PRODUCT_PORT: {{ .Values.product.service.port | quote }}

  API_PRODUCT_SERVICE_URL: "http://{{ include "ecommerce.fullname" . }}-product-service:{{ .Values.product.service.port }}"