apiVersion: v1
kind: Service

metadata:

  name: {{ include "ecommerce.fullname" . }}-product-db

  namespace: {{ .Release.Namespace }}


spec:

  selector:

    {{- include "ecommerce.selectorLabels" . | nindent 4 }}

    db: product-db


  ports:

    - port: 5432

      targetPort: 5432


  type: ClusterIP

  clusterIP: None


---
apiVersion: v1
kind: Service

metadata:

  name: {{ include "ecommerce.fullname" . }}-product-service

  namespace: {{ .Release.Namespace }}


spec:

  selector:

    {{- include "ecommerce.selectorLabels" . | nindent 4 }}

    app: product


  ports:

    - port: {{ .Values.product.service.port }}

      targetPort: {{ .Values.product.service.port }}


  type: ClusterIP