apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-products-db
  namespace: {{ .Release.Namespace}}
spec:
  selector:
    {{ include "ecommerce.selectorLabels" . | nindent 4}}
    db: products-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" .}}-product-service
  namespace: {{ .Release.Namespace}}

spec:
  selector:
    {{ include "ecommerce.selectorLabels" . | nindent 4}}
    app: product
  ports:
    - port: 9001
      targetPort: 9001
  type: ClusterIP
