apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-api-gateway-config
  namespace: {{ .Release.Namespace}}


data:
  API_USER_SERVICE_URL: "http://user-service:9002"
  API_PRODUCT_SERVICE_URL: "http://product-service:9001"
  API_CART_SERVICE_URL: "http://cart-service:9003"
  API_ORDER_SERVICE_URL: "http://order-service:9004"
  API_PAYMENT_SERVICE_URL: "http://payment-service:9005"

  API_ALLOWED_ORIGIN_PATTERNS: "http://192.168.49.2:30090 , http://international-commerce/ "


