apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce.fullname" . }}api-gateway-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ecommerce.selectorLabels" . | nindent 6 }}
      app: api-gateway
  template:
    metadata:
      labels:
        {{- include "ecommerce.selectorLabels" . | nindent 8 }}
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ineutrono/ecm-api-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-api-gateway-config
                  key: API_USER_SERVICE_URL
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-api-gateway-config
                  key: API_PRODUCT_SERVICE_URL
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-api-gateway-config
                  key: API_CART_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-api-gateway-config
                  key: API_ORDER_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-api-gateway-config
                  key: API_PAYMENT_SERVICE_URL
            - name: ALLOWED_ORIGIN_PATTERNS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-api-gateway-config
                  key: API_ALLOWED_ORIGIN_PATTERNS
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 40
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 40
            periodSeconds: 5