services:
  frontend:
    image: ineutrono/ecm-frontend-service:latest
    environment:
      - API_PROXY_TARGET=http://api-gateway:9000
    expose:
      - "3000"
    depends_on:
      - api-gateway
    networks:
      - ecommerce-net
    cpus: '.2'
    mem_limit: 200m
    restart: on-failure:3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      #no need while expose exist but its best practice in production and dont rely on auto detection, or we can use this for multiple labels , or no exposed
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

  redis:
    image: redis:7-alpine
    container_name: redis
    expose:
      - "6379"
    networks:
      - ecommerce-net
    restart: unless-stopped

  user-service:
    image: ineutrono/ecm-user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://accounts_db:5432/accounts_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4015
      - PORT=9002
    expose:
      - "9002"
    depends_on:
      accounts_db:
        condition: service_healthy
    networks:
      - ecommerce-net
      - database-net
    cpus: '.5'
    mem_limit: 700m
    restart: on-failure:3
    healthcheck:
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "wget -qO- http://localhost:9002/actuator/health | grep -q '\"status\":\"UP\"'"
          ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    #two networks on one service make traefik conflics so we need to add these labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ecommerce-net"

  product-service:
    image: ineutrono/ecm-product-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://products_db:5432/products_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4015
      - PRODUCT_SERVICE_URL=http://product-service:9001
      - PORT=9001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "9001"
    depends_on:
      products_db:
        condition: service_healthy
    networks:
      - ecommerce-net
      - database-net
    cpus: '.5'
    mem_limit: 700m
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9001/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    #two networks on one service make traefik conflics so we need to add these labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ecommerce-net"

  order-service:
    image: ineutrono/ecm-order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order_db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4015
      - CART_SERVICE_URL=http://cart-service:9003
      - PORT=9004
    expose:
      - "9004"
    depends_on:
      order_db:
        condition: service_healthy
    networks:
      - ecommerce-net
      - database-net
    cpus: '.5'
    mem_limit: 700m
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9004/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    #two networks on one service make traefik conflics so we need to add these labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ecommerce-net"

  payment-service:
    image: ineutrono/ecm-payment-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment_db:5432/payment_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4015
      - ORDER_SERVICE_URL=http://order-service:9004
      - PORT=9005
    expose:
      - "9005"
    depends_on:
      payment_db:
        condition: service_healthy
    networks:
      - ecommerce-net
      - database-net
    cpus: '.5'
    mem_limit: 700m
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9005/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    #two networks on one service make traefik conflics so we need to add these labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ecommerce-net"

  cart-service:
    image: ineutrono/ecm-cart-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cart_db:5432/cart_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4015
      - PRODUCT_SERVICE_URL=http://product-service:9001
      - PORT=9003
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    expose:
      - "9003"
    depends_on:
      cart_db:
        condition: service_healthy
    networks:
      - ecommerce-net
      - database-net
    cpus: '.5'
    mem_limit: 700m
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9003/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    #two networks on one service make traefik conflics so we need to add these labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ecommerce-net"

  api-gateway:
    image: ineutrono/ecm-api-service
    environment:
      - USER_SERVICE_URL=http://user-service:9002
      - PRODUCT_SERVICE_URL=http://product-service:9001
      - CART_SERVICE_URL=http://cart-service:9003
      - ORDER_SERVICE_URL=http://order-service:9004
      - PAYMENT_SERVICE_URL=http://payment-service:9005
    expose:
      - "9000"
    depends_on:
      user-service:
        condition: service_healthy

      product-service:
        condition: service_healthy

      order-service:
        condition: service_healthy

      payment-service:
        condition: service_healthy

      cart-service:
        condition: service_healthy
    networks:
      - ecommerce-net
    mem_limit: 400m
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/api`)"
      - "traefik.http.services.gateway.loadbalancer.server.port=9000"
      - "traefik.http.routers.gateway.priority=100"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls.certresolver=letsencrypt"
