services:
  accounts_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      POSTGRES_DB: accounts_db
    volumes:
      - accounts_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d accounts_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - database-net
    cpus: '.1'
    mem_limit: 70m
    restart: unless-stopped


  products_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      POSTGRES_DB: products_db
    volumes:
      - products_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d products_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - database-net
    cpus: '.1'
    mem_limit: 70m
    restart: unless-stopped

  order_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      POSTGRES_DB: order_db
    volumes:
      - order_data:/var/lib/postgresql/data
      - ../postgres-ha/primary/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ../postgres-ha/primary/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro

    command: "postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d order_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - database-net
    cpus: '.1'
    mem_limit: 70m
    restart: unless-stopped

  cart_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      POSTGRES_DB: cart_db
    volumes:
      - cart_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cart_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - database-net
    cpus: '.1'
    mem_limit: 70m
    restart: unless-stopped

  payment_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      POSTGRES_DB: payment_db
    volumes:
      - payment_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d payment_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - database-net
    cpus: '.1'
    mem_limit: 70m
    restart: unless-stopped

  backup:
    build:
      context: ./backups
      dockerfile: Dockerfile
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      PGAPASSWORD: 4015

    volumes:
      - ./backups:/backups

    depends_on:
      accounts_db:
        condition: service_healthy
      products_db:
        condition: service_healthy
      order_db:
        condition: service_healthy
      cart_db:
        condition: service_healthy
      payment_db:
        condition: service_healthy


    networks:
      - database-net
  order_db_standby:
    image: postgres:15

    user: postgres

    environment:
      PGPASSWORD: replica_pass

    volumes:
      - order_standby_data:/var/lib/postgresql/data
      - ./postgres-ha/standby/init-standby.sh:/usr/local/bin/init-standby.sh:ro

    entrypoint: [ "/bin/bash", "/usr/local/bin/init-standby.sh" ]

    depends_on:
      order_db:
        condition: service_healthy

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d order_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - database-net

    cpus: '.1'
    mem_limit: 70m
    restart: unless-stopped
  