services:
  accounts_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      POSTGRES_DB: accounts_db
    volumes:
      - accounts_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d accounts_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - database-net
    cpus: '.1'
    mem_limit: 70m
    restart: unless-stopped


  products_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      POSTGRES_DB: products_db
    volumes:
      - products_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d products_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - database-net
    cpus: '.1'
    mem_limit: 70m
    restart: unless-stopped

  order_db:
    build:
      context: ../postgres-ha/patroni
      dockerfile: Dockerfile

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      POSTGRES_DB: haproxy

    volumes:
      - order_data:/var/lib/postgresql/data
      - ../postgres-ha/patroni/patroni-primary.yml:/etc/patroni.yml:ro


    depends_on:
      etcd:
        condition: service_started

    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:8008/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

    networks:
      - database-net

    restart: unless-stopped

  cart_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      POSTGRES_DB: cart_db
    volumes:
      - cart_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cart_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - database-net
    cpus: '.1'
    mem_limit: 70m
    restart: unless-stopped

  payment_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      POSTGRES_DB: payment_db
    volumes:
      - payment_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d payment_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - database-net
    cpus: '.1'
    mem_limit: 70m
    restart: unless-stopped

  backup:
    build:
      context: ./backups
      dockerfile: Dockerfile
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4015
      PGAPASSWORD: 4015

    volumes:
      - ./backups:/backups

    depends_on:
      accounts_db:
        condition: service_healthy
      products_db:
        condition: service_healthy
      order_db:
        condition: service_healthy
      cart_db:
        condition: service_healthy
      payment_db:
        condition: service_healthy


    networks:
      - database-net


  order_db_standby:
    build:
      context: ../postgres-ha/patroni
      dockerfile: Dockerfile

    volumes:
      - order_standby_data:/var/lib/postgresql/data
      - ../postgres-ha/patroni/patroni-standby.yml:/etc/patroni.yml:ro

    depends_on:
      etcd:
        condition: service_started
      order_db:
        condition: service_started

    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:8008/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

    networks:
      - database-net

    restart: unless-stopped

  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.21

    command: "/usr/local/bin/etcd --name etcd1 --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://etcd:2380 --initial-cluster etcd1=http://etcd:2380 --initial-cluster-state new"

    volumes:
      - etcd_data:/etcd-data

    networks:
      - database-net

    restart: unless-stopped

  haproxy:
    image: haproxy:3.1

    volumes:
      - ../postgres-ha/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

    depends_on:
      order_db:
        condition: service_started
      order_db_standby:
        condition: service_started

    networks:
      - database-net

    restart: unless-stopped
