include:
  - databases.yml
  - ../monitoring/docker-compose.yml

networks:
  ecommerce-net:
    driver: bridge

  database-net:
    driver: bridge

  monitoring-net:
    driver: bridge

volumes:
  postgres_data:
  grafana-data:
  alertmanager-data:

services:
  cart-service:
    image: ineutrono/ecm-cart-service:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cart_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4015
      - PRODUCT_SERVICE_URL=http://100.65.115.41:9001
      - PORT=9003
      - REDIS_HOST=100.65.115.41
      - REDIS_PORT=6379
    ports:
      - "9003:9003"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecommerce-net
      - database-net
    cpus: '.5'
    mem_limit: 700m
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9003/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  order-service:
    image: ineutrono/ecm-order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4015
      - CART_SERVICE_URL=http://cart-service:9003
      - PORT=9004
    ports:
      - "9004:9004"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecommerce-net
      - database-net
    cpus: '.5'
    mem_limit: 700m
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9004/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  payment-service:
    image: ineutrono/ecm-payment-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payment_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4015
      - ORDER_SERVICE_URL=http://order-service:9004
      - PORT=9005
    ports:
      - "9005:9005"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecommerce-net
      - database-net
    cpus: '.5'
    mem_limit: 700m
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9005/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

