include:
  - ./backups/docker-compose.yml
  - app.yml
  - databases.yml
  - proxy.yml
  - ../monitoring/docker-compose.yml

networks:
  backend-net:
    driver: bridge
    name: backend-net

  frontend-net:
    driver: bridge
    name: frontend-net

  database-net:
    driver: bridge
    name: database-net

  monitoring-net:
    driver: bridge
    name: monitoring-net

volumes:
  payment_data:
  products_data:
  order_data:
  cart_data:
  accounts_data:
  postgres_backups:
  grafana-data:
  alertmanager-data:
