include:
  - app.yml
  - databases.yml
  - proxy.yml
  - ../monitoring/docker-compose.yml

networks:
  ecommerce-net:
    driver: bridge

  database-net:
    driver: bridge

  monitoring-net:
    driver: bridge

volumes:
  postgres_data:
  grafana-data:
  alertmanager-data:
