services:
  traefik:
    image: traefik:v3.7
    #opens dashboard with no security (for testing , in production i'will use dashboard + basic auth or Oauth  , provider will be used is docker , log shows info , error
    #command: --api.insecure=true --providers.docker --log.level=INFO
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #traefik read only from docker sock so he cant modify or delete
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic.yml
      - ./acme.json:/etc/traefik/acme.json

    networks:
      - frontend-net
      - backend-net
