services:
  traefik:
    image: traefik:v3.7
    #opens dashboard with no security (for testing , in production i'will use dashboard + basic auth or Oauth  , provider will be used is docker , log shows info , error
    #command: --api.insecure=true --providers.docker --log.level=INFO
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic.yml
      - ./acme.json:/etc/traefik/acme.json

    networks:
      - ecommerce-net

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

