apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-payment-config
  namespace: {{ .Release.Namespace }}

data:
  PAYMENT_SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "ecommerce.fullname" . }}-payment-db:5432/payment_db"

  PAYMENT_POSTGRES_DB: "payment_db"

  PAYMENT_ORDER_SERVICE_URL: "http://{{ include "ecommerce.fullname" . }}-order-service:{{ .Values.order.service.port }}"

  PAYMENT_PORT: {{ .Values.payment.service.port | quote }}

  API_PAYMENT_SERVICE_URL: "http://{{ include "ecommerce.fullname" . }}-payment-service:{{ .Values.payment.service.port }}"