apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce.fullname" . }}-payment-deployment
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "ecommerce.selectorLabels" . | nindent 6 }}
      app: payment

  template:
    metadata:
      labels:
        {{- include "ecommerce.selectorLabels" . | nindent 8 }}
        app: payment

    spec:
      containers:
        - name: payment

          image: "{{ .Values.payment.image.repository }}:{{ .Values.payment.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.payment.service.port }}

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-payment-config
                  key: PAYMENT_SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.secrets.dbUsername | quote }}

            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.secrets.dbPassword | quote }}

            - name: JWT_SECRET
              value: {{ .Values.secrets.jwtSecret | quote }}

            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-payment-config
                  key: PAYMENT_ORDER_SERVICE_URL

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ecommerce.fullname" . }}-payment-config
                  key: PAYMENT_PORT

          resources:
{{ toYaml .Values.resources | nindent 12 }}

          startupProbe:
            tcpSocket:
              port: {{ .Values.payment.service.port }}
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}

          livenessProbe:
            tcpSocket:
              port: {{ .Values.payment.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

          readinessProbe:
            tcpSocket:
              port: {{ .Values.payment.service.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}