apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" .}}-auth-config
  namespace: {{ .Release.Namespace}}

data:
  ACCOUNTS_POSTGRES_DB: "accounts_db"
  USER_PORT: "9002"
  API_USER_SERVICE_URL: "http://user-service:9002"
  USER_SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "ecommerce.fullname" . }}-accounts-db:5432/accounts_db"