apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-auth-config
  namespace: {{ .Release.Namespace }}

data:
  ACCOUNTS_POSTGRES_DB: "accounts_db"

  USER_PORT: {{ .Values.user.service.port | quote }}

  API_USER_SERVICE_URL: "http://{{ include "ecommerce.fullname" . }}-user-service:{{ .Values.user.service.port }}"

  USER_SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "ecommerce.fullname" . }}-accounts-db:5432/accounts_db"