apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-accounts-db
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    {{- include "ecommerce.selectorLabels" . | nindent 4 }}
    db: accounts-db

  ports:
    - port: 5432
      targetPort: 5432

  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-user-service
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    {{- include "ecommerce.selectorLabels" . | nindent 4 }}
    app: user

  ports:
    - port: {{ .Values.user.service.port }}
      targetPort: {{ .Values.user.service.port }}

  type: ClusterIP