apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-alertmanager-config
  namespace: {{ .Release.Namespace }}

data:
  alertmanager.yml: |
    global:
      smtp_smarthost: {{ .Values.alertmanager.config.global.smtpSmarthost | quote }}
      smtp_from: {{ .Values.alertmanager.config.global.smtpFrom | quote }}

    route:
      receiver: {{ .Values.alertmanager.config.route.receiver | quote }}
      group_wait: {{ .Values.alertmanager.config.route.groupWait | quote }}
      group_interval: {{ .Values.alertmanager.config.route.groupInterval | quote }}
      repeat_interval: {{ .Values.alertmanager.config.route.repeatInterval | quote }}

    receivers:
      - name: {{ .Values.alertmanager.config.receivers.name | quote }}
        email_configs:
          - to: {{ .Values.alertmanager.config.receivers.emailConfigs.to | quote }}