apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-alertmanager
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.alertmanager.service.type }}

  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
    app: alertmanager

  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: {{ .Values.alertmanager.service.targetPort }}
      protocol: TCP