namespace: argocd
project: default

application:
  name: ecommerce

  source:
    repoURL: https://github.com/Mohamed3bkreem404/International-Commerce.git
    targetRevision: main
    path: helm/ecommerce

  destination:
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    automated: true
    prune: true
    selfHeal: true
    createNamespace: true

monitoring:
    name: monitoring

    source:
      repoURL: https://github.com/Mohamed3bkreem404/International-Commerce.git
      targetRevision: main
      path: helm/monitoring

    destination:
      server: https://kubernetes.default.svc
      namespace: monitor

    syncPolicy:
      automated: true
      prune: true
      selfHeal: true
      createNamespace: true