apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.application.name}}-project
  namespace: {{ .Values.namespace}}
spec:
  description: Simple project for ecommerce app

  sourceRepos:
    - {{.Values.application.source.repoURL}}
  destinations:
    - namespace: {{ .Values.application.destination.namespace}}
      server: {{ .Values.application.destination.server}}
      #Here permit charts to create ns
{{/*  clusterResourceBlacklist:*/}}
{{/*    - group: ""*/}}
{{/*      kind: Namespace*/}}
      #Allowed resources to create
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment

    - group: apps
      kind: StatefulSet

    - group: ""
      kind: Service

    - group: ""
      kind: ConfigMap

    - group: ""
      kind: Secret

    - group: ""
      kind: PersistentVolumeClaim

    - group: networking.k8s.io
      kind: Ingress

    - group: autoscaling
      kind: HorizontalPodAutoscaler

    - group: policy
      kind: PodDisruptionBudget