apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name}}
  namespace: {{ .Values.namespace}}
spec:
  project: {{ .Values.application.name}}-project
  source:
    repoURL: {{ .Values.application.source.repoURL}}
    #branch
    targetRevision: {{ .Values.application.source.targetRevision}}
    path: {{ .Values.application.source.path}}
  destination:
    server: {{ .Values.application.destination.server}}
    namespace: {{.Values.application.destination.namespace}}
  syncPolicy:
    automated:
      prune: {{ .Values.application.syncPolicy.prune}}
      selfHeal: {{ .Values.application.syncPolicy.selfHeal}}