apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.grafana.replicaCount }}

  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
      app: grafana

  template:
    metadata:
      labels:
        {{- include "monitoring.selectorLabels" . | nindent 8 }}
        app: grafana

    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.grafana.service.targetPort }}
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources

            - name: provisioning
              mountPath: /etc/grafana/provisioning/dashboards

            - name: dashboards
              mountPath: /var/lib/grafana/dashboards

      volumes:
        - name: datasources
          configMap:
            name: grafana

        - name: provisioning
          configMap:
            name: grafana

        - name: dashboards
          configMap:
            name: grafana