apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.grafana.service.type }}

  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
    app: grafana

  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
      protocol: TCP
      {{- if eq .Values.grafana.service.type "NodePort" }}
      nodePort: {{ .Values.grafana.service.nodePort }}
      {{- end }}