name: Deploy Order Service

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Image Version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: Order Service/Order-Service
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        working-directory: Order Service/Order-Service
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/ecm-order-service:${{ env.VERSION }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/ecm-order-service:latest \
            .

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecm-order-service:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecm-order-service:latest

#      - name: Deploy to Kubernetes via SSH
#        uses: appleboy/ssh-action@v1.2.0
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            cd /home/ubuntu/International-Commerce
#            git pull origin main
#
#            kubectl set image deployment/order-deployment \
#              order-service=${{ secrets.DOCKERHUB_USERNAME }}/ecm-order-service:${{ env.VERSION }} \
#              -n ecommerce-v2
#
#            kubectl rollout status deployment/order-deployment -n ecommerce-v2