- name: Create and Apply K8s Secrets
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      sudo kubectl create secret generic ecommerce-secrets \
        --namespace=ecommerce-v2 \
        --from-literal=DB_USER=postgres \
        --from-literal=DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
        --from-literal=JWT_SECRET='${{ secrets.JWT_SECRET }}' \
        --dry-run=client -o yaml | sudo kubectl apply -f -